--- #YAML:1.0
name:                       Labyrinth-Plugin-Articles-Profiles
version:                    1.02
abstract:                   Profiles plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                    artistic_2
distribution_type:          module
installdirs:                site

requires:
  perl:                     5.006
  Labyrinth:                5.28
  Labyrinth::Plugin::Core:  5.18
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Labyrinth::Test::Harness: 1.05
  Test::More:               0.70

provides:
  Labyrinth::Plugin::Articles::Profiles:
    file:     lib/Labyrinth/Plugin/Articles/Profiles.pm
    version:  1.02

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  homepage:   http://labyrinth.missbarbell.co.uk
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Articles-Profiles
  repository: http://github.com/barbie/labyrinth-plugin-articles-profiles

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
